### Numpy

The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

<img src="fig0.png"
    style="float: left;"></img>

In [1]:
import numpy as np

#### Creating Arrays

In [2]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)
d = np.arange(10,25,5)
e = np.full((2,2),7)
f = np.eye(2)

In [3]:
np.zeros((3,4))                   #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((2,3,4),dtype=np.int16)   #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [5]:
np.arange(10,25,5)               #Create an array of evenly spaced values (step value)

array([10, 15, 20])

In [6]:
np.linspace(0,2,9)                #Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
np.full((2,2),7)                 #Create a constant array

array([[7, 7],
       [7, 7]])

In [8]:
np.eye(2)                         #Create a 2X2 identity matrix

array([[1., 0.],
       [0., 1.]])

In [9]:
np.random.random((2,2))           #Create an array with random values

array([[0.84788349, 0.40150001],
       [0.99806681, 0.3871844 ]])

In [10]:
np.empty((3,2))                   #Create an empty array

array([[4.65789201e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

#### Saving & Loading On Disk

In [11]:
#np.save('my_array', a)
#np.savez('array.npz', a, b)
#np.load('my_array.npy')

array([1, 2, 3])

#### Data Types

| type | definition |
| :-- | :-- |
| np.int64 | Signed 64-bit integer types
| np.float32 | Standard double-precision floating point
| np.complex | Complex numbers represented by 128 floats
| np.bool | Boolean type storing TRUE and FALSE values
| np.object | Python object type
| np.string_ | Fixed-length string type
| np.unicode_ | Fixed-length unicode type

#### Inspecting Your Array

In [12]:
a.shape                         #Array dimensions

(3,)

In [13]:
len(a)                          #Length of array

3

In [14]:
b.ndim                          #Number of array dimensions

2

In [15]:
e.size                          #Number of array elements

4

In [16]:
b.dtype                         #Data type of array elements

dtype('float64')

In [17]:
b.dtype.name                    #Name of data type

'float64'

In [18]:
b.astype(int)                   #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

#### Array Arithmetic

In [19]:
g = a - b                       #Subtraction
np.subtract(a,b)                #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [20]:
b + a                           #Addition
np.add(b,a)                     #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [21]:
a / b                           #Division
np.divide(a,b)                  #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [22]:
a * b                           #Multiplication
np.multiply(a,b)                #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [23]:
np.exp(b)                       #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [24]:
np.sqrt(b)                      #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [25]:
e.dot(f)                        #Dot product

array([[7., 7.],
       [7., 7.]])

#### Comparison

In [26]:
a == b                          #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [27]:
a < 2                           #Element-wise comparison

array([ True, False, False])

In [28]:
np.array_equal(a, b)            #Array-wise comparison

False

#### Aggregate Functions

| function | definition |
| :-- | :-- |
| a.sum() | Array-wise sum
| a.min() | Array-wise minimum value
| b.max(axis=0) | Maximum value of an array row
| b.cumsum(axis=1) | Cumulative sum of the elements
| a.mean() | Mean
| b.median() | Median
| a.corrcoef() | Correlation coefficient
| np.std(b) | Standard deviation


#### Copying Arrays

In [29]:
h = a.view()                    #Create a view of the array with the same data

In [30]:
np.copy(a)                      #Create a copy of the array

array([1, 2, 3])

In [31]:
h = a.copy()                    #Create a deep copy of the array

#### Sorting Arrays

In [32]:
a.sort()                        #Sort an array

In [33]:
c.sort(axis=0)                  #Sort the elements of an array's axis

#### Subsetting

In [34]:
a[2]

3

<img src="fig1.png">

In [35]:
b[1,2]

6.0

<img src="fig2.png">

In [36]:
a[0:2]

array([1, 2])

<img src="fig3.png">

In [37]:
b[0:2,1]

array([2., 5.])

<img src="fig4.png">

In [38]:
b[:1]

array([[1.5, 2. , 3. ]])

<img src="fig5.png">

In [39]:
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [40]:
a[ : :-1]

array([3, 2, 1])

#### Boolean Indexing

In [41]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

#### Fancy Indexing

In [42]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [43]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

#### Array Manipulation 

In [44]:
i = np.transpose(b)             #Permute array dimensions
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [45]:
b.ravel()                       #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [46]:
g.reshape(3,-2)                 #Reshape, but don’t change data

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [47]:
h.resize((2,6))                 #Return a new array with shape (2,6)

In [48]:
np.append(h,g)                  #Append items to an array

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [49]:
np.insert(a, 1, 5)              #Insert items in an array

array([1, 5, 2, 3])

In [50]:
np.delete(a,[1])                #Delete items from an array

array([1, 3])

In [51]:
np.concatenate((a,d),axis=0)    #Concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [54]:
np.vstack((a,b))                #Stack arrays vertically (row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [55]:
np.hstack((e,f))                #Stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [56]:
np.column_stack((a,d))          #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [57]:
np.c_[a,d]                      #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [59]:
np.hsplit(a,3)                  #Split the array horizontally at the 3rd index


[array([1]), array([2]), array([3])]

In [60]:
np.vsplit(c,2)                  #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]